### PR TITLE
do not need decode to str when deserialize json to Python object

### PR DESCRIPTION
**Pull request by erhuabushuo**
[https://github.com/python/cpython/blob/71ef0b4c2b77195bb1adc42602549284f7ee9566/Lib/json/__init__.py#L301](https://github.com/python/cpython/blob/71ef0b4c2b77195bb1adc42602549284f7ee9566/Lib/json/__init__.py#L301)

"""Deserialize ``s`` (a ``str``, ``bytes`` or ``bytearray`` instance
    containing a JSON document) to a Python object.

json.loads may accept  str, bytes, bytearray, we don't need decode to str

### CODE REVIEW

**Comment by erhuabushuo** [comment]
_get_standardized_value is not working when json payload contains bool, float and None type.

```
if isinstance(value, (str, int, dict)):
        return value
```
json may contains bool, float, and None type.

**Comment by josephmancuso** [comment]
I'll have to manually

**Comment by erhuabushuo** [comment]
wow, I didn't modify src/masonite/drivers/authentication/AuthJwtDriver.py:13:1: E303 too many blank lines (3)

**Comment by erhuabushuo** [comment]
lint code

**Comment by josephmancuso** [comment]
@erhuabushuo can I get a little explanation here? where did this issue come from and how to I test the use case which its broken for? I don't like merging in code I don't understand

**Comment by josephmancuso** [comment]
@girardinsamuel this should be good to merge right? Code looks good and tests pass though im still kind of confused on what the issue originally was

**Comment by girardinsamuel** [comment]
> @girardinsamuel this should be good to merge right? Code looks good and tests pass though im still kind of confused on what the issue originally was

Let me check locally first.

**Comment by erhuabushuo** [comment]
POST_DATA may be "application/json" content, the json content may contains float, bool and None .

currently if json contain these type (bool, float, None) will be raised exception,

```
if isinstance(value, (str, int, dict)):  # here can't be true
        return value


if not value.filename: # here will be raise exception, cause bool , float and None don't have the property of filename .
        return value.value
```

**Pull request merged**
