### PR TITLE
Add Tailwind 2 preset

### PR DESCRIPTION
**Pull request by girardinsamuel**
This PR adds a preset for Tailwind 2.X ! It's based on new npm dependencies introduced in masonite 3.0 project templates.
This time, I choosed that the preset updates the default templates so that the project is directly tailwind ready !

Here is what it looks like 🎉  (with tailwind css styling of course)

image

### CODE REVIEW

**Comment by girardinsamuel** [comment]
This time, I choosed that the preset updates the default templates so that the style is directly integrated.
Here is what it looks like 🎉  (with tailwind css styling of course)
image

**Comment by Marlysson** [comment]
@girardinsamuel The tailwind css icon appear there cause there tailwind installed? What do you thing of add all of the installed prests too? Vue|React & Tailwind... Indicating the things that are build with.

**Comment by girardinsamuel** [comment]
@Marlysson 
> The tailwind css icon appear there cause there tailwind installed? What do you thing of add all of the installed prests too? Vue|React & Tailwind... Indicating the things that are build with.

I added the icon my self via the preset. It does not magically appears because tailwind is loaded in the page 😉 .
You mean add the icon on the "/" view for each of the preset ?

**Comment by girardinsamuel** [comment]
@josephmancuso @Marlysson I had questions about installing Tailwind with Masonite so here is a preset of Tailwind  2.X compatible with masonite 3 projects.

It's good to remind that until masonite 3.0 release, to craft new project with correct template we must specify template version `craft new -b 3.0` else the version will be the 2.X version (with old npm dependencies).
So if you want to test the preset:
- create a venv with this version of masonite (e.g. `pip install git+https://github.com/girardinsamuel/masonite@feat/add-tailwind-preset`)
- `craft new -b 3.0`
- `craft preset tailwind2`
- `npm install && npm run dev``
- browse to `http://localhost:8000` 🎉 


BTW @josephmancuso how maintain ability to craft project with 2.X and 3.X ? I mean it's working with `-b` flag but when masonite 3.X will be officially released what will be the behaviour of `craft new` without flag ? I guess it should craft cookie-cutter 3.0 projects !

**Comment by josephmancuso** [comment]
@girardinsamuel the branch used is entirely based on the repo releases.In order for craft new to build a 3.0 branch we need to release the 3.0 branch in the repo

**Comment by josephmancuso** [comment]
Thats basically the last step to release the project live is to release the Masonite repo and then immediately release the cookie cutter repo.

**Comment by girardinsamuel** [comment]
> @girardinsamuel the branch used is entirely based on the repo releases.In order for craft new to build a 3.0 branch we need to release the 3.0 branch in the repo

What do you mean by release ? It's already the case isn't it ? 3.0 branch exists in cookie-cutter.

**Comment by girardinsamuel** [comment]
craft new without anything else is using latest version of master branch

**Comment by josephmancuso** [comment]
hmm that sounds right lol

**Review by josephmancuso — APPROVED** [review]

**Pull request merged**
