### PR TITLE
updates craft mailable command description

### LINKED ISSUE #237: craft mailable command description
**Describe the bug**
Screenshot from 2020-02-03 13-40-06

**Expected behavior**
Maybe add "Creates a new mailable" as description.

### PR DESCRIPTION
**Pull request by sumit4613**
Closes #237

### CODE REVIEW

**Comment by josephmancuso** [comment]
that was fast! LGTM (Looks good to me) 👍

**Comment by sumit4613** [comment]
> that was fast! LGTM (Looks good to me) 👍

Thanks for merging it, it was my first open source contribution. :heart_eyes:

**Comment by josephmancuso** [comment]
WOW nice!! Welcome to the community!

**Comment by sumit4613** [comment]
> WOW nice!! Welcome to the community!

Thank you, it’s good to be here! :smile:

**Pull request merged**
