### PR TITLE
Allow unbound class resolution from container

### LINKED ISSUE #618: Allow unbound class resolution from container
### Is your feature request related to a problem?

Currently, resolving a dependency from the container requires previously binding that class in some manner explicitly, even if all that is required to "resolve" the class is to simply instantiate it as `AnyClass()`.

Any sufficiently large and complex application will require dozens of such rote bindings.

**The proposal here is to make container resolution have a simple form of non-bound resolution as the fallback when an explicit binding does not exist.**

This would improve developer experience by removing the code needed to add a `.simple()` binding somewhere, likely inside a ServiceProvider.

Moreover, this already partially exists in Controller resolution within HTTPRoute:

```python
self.controller_class = Loader.get_object(
    controller.__module__, controller_name, raise_exception=True
)

...

controller = self.controller_class()

return getattr(controller, self.controller_method)()
```

### What do we currently have to do now?

Exception case:

```python
class AnyClass:
    pass

# never bound via self.application.bind/simple/etc
instance = self.application.make(AnyClass)

# src.masonite.exceptions.exceptions.MissingContainerBindingNotFound: The dependency with the <class 'AnyClass'> annotation could not be resolved by the container
```

Working case:

```python
class AnyClass:
    pass

self.application.simple(AnyClass)

instance = self.application.make(AnyClass)

true == isinstance(instance, AnyClass)
```

### Describe the solution you'd like

```python
class AnyClass:
    pass

# never bound via self.application.bind/simple/etc
instance = self.application.make(AnyClass)

true == isinstance(instance, AnyClass)
```

### Describe alternatives you've considered

_No response_

### Would this be a breaking change ?

No

### Anything else ?

This would be backwards compatible with existing bindings since it would be implemented as a fallback.

Resolution would still fail if arguments are necessary when instantiating and they cannot be resolved (e.g., str, int, etc).

Resolvable dependencies in the `def __init__(...)` args within this "fallback" resolution should continue to be resolved.

### PR DESCRIPTION
**Pull request by girardinsamuel**
Fix #618.

### CODE REVIEW

**Comment by girardinsamuel** [comment]
@os-nikita I reopened your PR here.

@josephmancuso What do you think of this ? I reviewed it, it looks good to me 👌. The only thing is: what happens when we try to resolve somehting into the container which really does not exist ?

**Comment by os-nikita** [comment]
> The only thing is: what happens when we try to resolve somehting into the container which really does not exist ?

@girardinsamuel In which scenario do you envision that would happen? 🤔

**Comment by girardinsamuel** [comment]
Yes, I am not sure that this could happen. But somehow if the class is not imported correctly and we try to resolve it, will the error be caught correctly ?

**Comment by os-nikita** [comment]
Let me do a few tests to confirm later today.

**Comment by josephmancuso** [comment]
> @os-nikita I reopened your PR here.
> 
> @josephmancuso What do you think of this ? I reviewed it, it looks good to me 👌. The only thing is: what happens when we try to resolve somehting into the container which really does not exist ?

@girardinsamuel I'm not sure what you mean here. What do you mean by class does not exist? If a class is not imported correctly, won't you get an import error?

And if you do import a class that's not right ... I am not sure I understand the issue lol

**Comment by os-nikita** [comment]
Yep that's my conclusion here as well. An import error will happen regardless of this PR, it does not do anything magical to get around that.

**Comment by os-nikita** [comment]
Perhaps the only thing I may add/adjust is the way the application/container itself is resolved using this approach. 🤔

**Comment by girardinsamuel** [comment]
You're right, should not be an issue finally..

> add/adjust is the way the application/container itself is resolved using this approach.

What do you mean here ?

**Comment by os-nikita** [comment]
If someone adds `foundation.Application` or `container.Container` as a dependency in a method.

**Comment by girardinsamuel** [comment]
> If someone adds `foundation.Application` or `container.Container` as a dependency in a method.

Oh yes, well it's not a good idea to do this. Do you want to add a safeguard for this ?

**Comment by josephmancuso** [comment]
> If someone adds `foundation.Application` or `container.Container` as a dependency in a method.

I'll have to test this use case but i believe the container binds itself to the container so that would work and resolve fine. The application class maybe not but i would think we can just bind the application class to the container as well.

On another note, if there are dependencies that are not in the container it would throw an error like "Cannot resolve parameter application: Application"

**Comment by os-nikita** [comment]
Something like this? 

https://github.com/os-nikita/masonite/commit/7c14c4c04e2f9d3e85de1c390f80fbb7dd8ab9dd

**Comment by os-nikita** [comment]
> On another note, if there are dependencies that are not in the container it would throw an error like "Cannot resolve parameter application: Application"

Did you mention this related to the container/application self-resolution discussion? Or in general? Because this PR was crafted especially to allow dependencies to be resolved automatically within method arguments e.g., in controllers. So the above error would no longer appear as long as the dependency can be correctly constructed. I added tests to demonstrate this using nested dependencies. Perhaps adding another test to see it in action with a controller would be clearer.

**Comment by girardinsamuel** [comment]
No that's okay for me 😉. I am not sure about the last one https://github.com/os-nikita/masonite/commit/7c14c4c04e2f9d3e85de1c390f80fbb7dd8ab9dd though...else it's good to me !

@josephmancuso can you do a final review ?

**Review by josephmancuso — APPROVED** [review]

**Comment by josephmancuso** [comment]
> > On another note, if there are dependencies that are not in the container it would throw an error like "Cannot resolve parameter application: Application"
> 
> Did you mention this related to the container/application self-resolution discussion? Or in general? Because this PR was crafted especially to allow dependencies to be resolved automatically within method arguments e.g., in controllers. So the above error would no longer appear as long as the dependency can be correctly constructed. I added tests to demonstrate this using nested dependencies. Perhaps adding another test to see it in action with a controller would be clearer.

Yeah you are right.

**Comment by josephmancuso** [comment]
Merged in. PR looks great 👍 awesome job

**Comment by girardinsamuel** [comment]
Because of type hinting application with "Application" it looks like it give some issues now we are trying to resolve any classes...

**Comment by os-nikita** [comment]
@girardinsamuel What do you mean? There are issues now that this has been merged in? 🤔

**Comment by josephmancuso** [comment]
> @girardinsamuel What do you mean? There are issues now that this has been merged in? 🤔

I tested this on a test app and everything looked great but we think there could be some conflicts with local development having conflicts between the namespacing (src.masonite.response.Response vs masonite.response.Response)

**Comment by josephmancuso** [comment]
we're still investigating

**Comment by os-nikita** [comment]
> > @girardinsamuel What do you mean? There are issues now that this has been merged in? 🤔
> 
> I tested this on a test app and everything looked great but we think there could be some conflicts with local development having conflicts between the namespacing (src.masonite.response.Response vs masonite.response.Response)

I did see this at some point during testing when trying out the "self-resolving container" approach and was confused by this namespace difference.

**Comment by girardinsamuel** [comment]
Here is a PR adding more tests to container to demonstrate a potential issue.
https://github.com/MasoniteFramework/masonite/pull/637
The two last tests are failing demonstrating issue that can arise from parameter type hinted with strings.

Note that the namespaced issue is another issue which is independant from the changes of this PR.

**Pull request merged**
