### PR TITLE
Add namespace parameter to RouteGroup Fix/226

### LINKED ISSUE #226: RouteGroup controller namespace
It would be great instead of writing something like this:
```
get('/register', 'auth.RegisterController@show'),
get('/login', 'auth.LoginController@show'),
```
 to do this:
```
RouteGroup([
    get('/register', 'RegisterController@show'),
    get('/login', 'LoginController@show'),
], namespace='auth.'),
```

### PR DESCRIPTION
**Pull request by tpow**
This adds the namespace parameter to RouteGroup and fixes #226.

One change I'd note:
Prior to this fix, some process (I'm not sure what) tries to find the controllers for all the routes up front. Because Routes are constructed before RouteGroups, this meant that you would get a bunch of "Cannot find controller" messages up front, then the RouteGroup would adjust the namespace and resolve properly. This was misleading, so I therefore moved the print to when you attempt to use the route. This aligns with when the exception is raised, but may make it more difficult to track down malformed routes since the controllers are not reported as malformed up front. 

Perhaps `craft show:routes` could be adjusted to resolve controllers? 

Alternatively -- I just thought of this -- perhaps the _namespace function could check for self.e after calling find_controller and show the print then. Or perhaps add a flag to find_controller to control whether or not to show the print. This would let it resolve the routes/routegroups and warn about them up front. Any thoughts?

Here are example routes that I used for testing:
```
from masonite.routes import RouteGroup, Get, Post                                
from app.http.controllers.auth.LoginController import LoginController            
                                                                                 
ROUTES = [
    # Auth Login Routes (same as Auth.routes() from craft auth)                                         
    RouteGroup([                                                                 
        Get('/login', 'LoginController@show').name('login'),                         
        Get('/logout', 'LoginController@logout').name('logout'),                     
        Post('/login', 'LoginController@store'),                                     
        Get('/register', 'RegisterController@show').name('register'),                
        Post('/register', 'RegisterController@store'),                               
        Get('/home', 'HomeController@show').name('home'),                            
        Get('/email/verify', 'ConfirmController@verify_show').name('verify'),        
        Get('/email/verify/send', 'ConfirmController@send_verify_email'),            
        Get('/email/verify/@id:signed', 'ConfirmController@confirm_email'),          
        Get('/password', 'PasswordController@forget').name('forgot.password'),       
        Post('/password', 'PasswordController@send'),                                
        Get('/password/@token/reset', 'PasswordController@reset').name('password.reset'),
        Post('/password/@token/reset', 'PasswordController@update'),                 
                                                                                 
        Get('/missing', 'MissingController@show').name('missing'), # Testing a missing controller
    ], namespace='auth.'), # Note the namespace!                                                      
                                                                                 
    # More routes with prefix and namespaces
    RouteGroup([                                                                 
        Get('/login', 'LoginController@show'),             
        Get('/register', 'RegisterController@show').name('register'),
        Get('/loginb', LoginController.show).name('loginb'), # Testing Controller object reference
    ], prefix='/authprefix', name='authorize.', namespace='auth.'),
]
```

URLs to test:
```
/login  - should resolve correctly
/register - should resolve correctly
... all the normal craft auth URLs work
/missing - should fail with an exception and print the cannot find controller message

/authprefix/login - should resolve and show normal login form
/authprefix/register - show resolve and show normal register form
/authprefix/loginb - should also show the login form
```

As the comment shows, when using the (probably rarely used) controller object reference, the namespace is ignored. I figure if you wanted it, you'd provide it in the import. This lets you use a combination of string and object references in the same RouteGroup. (Not sure why you would want to do this or if anyone would.)

I'm a little concerned about the potential for confusion between name (which gets added to named routes) and namespace, but haven't thought of a better solution. If anything, I'd change name since it is generic to name_prefix or something. This would be a breaking changing to existing RouteGroups, though.

### CODE REVIEW

**Comment by josephmancuso** [comment]
Thats amazing that you found out that issue on your own. That was the limiting factor as to why there was no namespace feature

**Comment by josephmancuso** [comment]
I tried to take a crack at this now and i didn't like my solution. On a good note though I pushed 2 new files to the PR. One is a test. Get the test to pass and you're good!

**Comment by tpow** [comment]
I apologize that I hadn't noticed the tests previously. I would have updated them and run them otherwise. 

I noticed that the subcontroller test failed on the format used in the test, Get().route(...), but not with the syntax that seems to be preferred using the constructor Get(route_url, controller_reference). I had only tested with the constructor syntax. I added another test to check this and then revised it to make it a more complex "deep" test.

**Comment by tpow** [comment]
The tests pass now. I also added a few.

I thought it would be convenient to specify namespaces with or without the trailing dot, so I added support (and a test) for that. This lets you use namespace="auth" as well as namespace="auth." If you disagree, feel free to revert the last commit.

Let me know if anything else needs to be changed. Thanks!

**Comment by tpow** [comment]
@josephmancuso What's the next step in getting this pull request merged?

**Comment by josephmancuso** [comment]
Let me do a manual review of it and if it’s good I’ll merge it in and cut a release. I’ve been focusing a lot of my time on the orm project. I should be able to get to it tonight

**Comment by josephmancuso** [comment]
changing base to master and getting it up to date

**Comment by tpow** [comment]
Thanks!

**Pull request merged**
