### PR TITLE
Added `boolean` validation rule

### PR DESCRIPTION
**Pull request by BSN4**

### CODE REVIEW

**Comment by girardinsamuel** [comment]
It looks good for now 😉

**Comment by girardinsamuel** [comment]
@if4lcon is this PR is complete ? You can request a review from the maintainers with the GitHub button on the right (me or Joe) 😉.

**Comment by BSN4** [comment]
> @if4lcon is this PR is complete ? You can request a review from the maintainers with the GitHub button on the right (me or Joe) 😉.

@girardinsamuel yes its complete . I will do this now sorry didn't know about the request

**Review by BSN4 — COMMENTED** [review]
done

**Comment by BSN4** [comment]
@girardinsamuel  from Github source : 

> 
> This feature is only for the owner of the repository, not for the author of the pull request.
> The pull request author still can't request anyone to review his request.
> The only way is to mention the person in a comment.

**Review by girardinsamuel — APPROVED** [review]

**Review by josephmancuso — APPROVED** [review]

**Pull request merged**
