### PR TITLE
Next Minor

### PR DESCRIPTION
**Pull request by josephmancuso**

### CODE REVIEW

**Comment by girardinsamuel** [comment]
@josephmancuso do you want to add those to the next minor ? 
* Vue 3.0 preset #340 
* update of Pusher driver and add new PubNub driver #351

**Comment by josephmancuso** [comment]
eh we can put it in the next major. They're non breaking changes but since we're so close to 3 we can just add them to 3.

**Comment by girardinsamuel** [comment]
@josephmancuso okay I will rebase the related PR to 3.0. What about this minor version, do you wait for adding other fixes/features, or should we merge it ?

**Review by girardinsamuel — APPROVED** [review]

**Comment by josephmancuso** [comment]
I usually merge it the same time I release it. Haven't gotten time to release this one yet. When I come back over to Masonite development I'll start clearing some of these out

**Comment by girardinsamuel** [comment]
> I usually merge it the same time I release it. Haven't gotten time to release this one yet. When I come back over to Masonite development I'll start clearing some of these out

Okay cool  ! I reviewed the changes so it's ready

**Pull request merged**
