### PR TITLE
Resource routes default names (Issue #416)

### LINKED ISSUE #416: Default resource route names
When we create a Resource route like this

Resource('products', 'ProductsController')

It will be great if Masonite can give default route name (like in Laravel):
products.index
products.create
products.store
products.edit
products.update
products.destroy

I know we can specified the name manually like this
Resource('products', 'ProductsController', names={'index': 'products.index')

That method is ok when we need custom name but it will be great not to have to enter default value each time.

If you approve this modification, I would like to code it myself :-) That could be my first contribution to the framework.

### PR DESCRIPTION
**Pull request by rickavmaniac**
Hi,

Ok first pull request in life so be gentle...

Do not hesitate to give me any advice/instruction.

Closes #416

### CODE REVIEW

**Comment by rickavmaniac** [comment]
Hi,

 I need help with this one. The lint error is on a file I did not touch and not sure I understand the DeepSource error?

**Comment by girardinsamuel** [comment]
> I need help with this one. The lint error is on a file I did not touch and not sure I understand the DeepSource error?

- For the linting issue, you can fix it in this PR even if it's not related to your changes (as this one is really quick to fix)
- Well don't bother with the deepsource if it's not related to your changes.
- Also you should refer to the issue you're working on (in a PR comment) so that merging the PR will close the issue (https://docs.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword)

Otherwise it's looks good and you add testing so that's cool !

**Comment by rickavmaniac** [comment]
Closes #416

**Comment by rickavmaniac** [comment]
Not sure about this one... Do I need to close the pull request or only after merge?

**Comment by girardinsamuel** [comment]
> Not sure about this one... Do I need to close the pull request or only after merge?

No, one of the repo maintainer, should review it and merge it (this will merge your changes, close the PR and close the issue) 😉 
@josephmancuso ready for review !

**Comment by josephmancuso** [comment]
Ok thanks. FYI the automatic issue closing with "Closes #issue_number" only works if thats inside the original PR description. (the first comment box created with the PR). Won't work inside a comment. 

I'll review this PR when i get some time. Everything looks good tho

**Review by josephmancuso — APPROVED** [review]

**Pull request merged**
